apiVersion: apps/v1
kind: Deployment
metadata:
  name: webby
  labels:
    app: webby
spec:
  selector:
    matchLabels: 
      app: webby
  replicas: 3 
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby
        image: webby
        ports:
        - containerPort: 80
